<a href="https://colab.research.google.com/github/Shalyne-Waweru/Independent_Project-4/blob/master/Moringa_Data_Science_Prep_W4_Independent_Project_2020_03_Shalyne_Waweru_Python_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Independent Project: Week 4

**Research Question**

You will be working as a data scientist working for an electric car-sharing service company. You have been tasked to process stations data to understand electric car usage over time and identify the most popular hour of the day for picking up a shared electric car (Bluecar) in the city of Paris over the month of April 2018.

**Possible Questions for Consideration**



*   What is the most popular hour for returning cars?
*   What is the overall most popular station?
*   What is the most popular station at the most popular picking hour?
*   What the overall most popular postal code for picking up Blue cars? Check whether it matches the most popular station
*   What is the most popular postal code at the most popular picking hour? Check whether it matches the most popular station
*   Do the results change if you consider Utilib and Utilib 1.4 instead of Blue cars? 

**Datasets Provided**


*   Autoib_dataset [http://bit.ly/autolib_dataset (Links to an external site.)]
*   Dataset description [https://drive.google.com/file/d/13DXF2CFWQLeYxxHFekng8HJnH_jtbfpN/view ]

# Importing The Libraries

In [0]:
# Import the pandas library and the numpy library
#
import pandas as pd
import numpy as np

# Loading the Dataset

In [4]:
# Loading the data from the csv file into a dataframe to be used
#
df_auto = pd.read_csv("Autolib_dataset (2).csv", delimiter = ',')
df_auto

                                 Address  Cars  ...  hour  minute
0                    2 Avenue de Suffren     0  ...    11      43
1              145 Rue Raymond Losserand     6  ...     7      24
2       2 Avenue John Fitzgerald Kennedy     3  ...    20      14
3                 51 Rue EugÃ¨ne OudinÃ©     3  ...     4      37
4     6 avenue de la Porte de Champerret     3  ...    17      23
...                                  ...   ...  ...   ...     ...
4995                 8 avenue MÃ©nelotte     2  ...    11      26
4996                   37 rue de Dantzig     4  ...    16      56
4997                      142 rue du Bac     1  ...     7       1
4998         2 avenue du Val de Fontenay     2  ...    17      27
4999                 5 Rue Henry Brisson     4  ...    10       2

[5000 rows x 25 columns]

# Previewing the Dataset

In [5]:
# Previewing the first 10 rows of the data
#
df_auto.head(10)

                              Address  Cars  Bluecar counter  ...  day  hour  minute
0                 2 Avenue de Suffren     0                0  ...    8    11      43
1           145 Rue Raymond Losserand     6                6  ...    6     7      24
2    2 Avenue John Fitzgerald Kennedy     3                3  ...    3    20      14
3              51 Rue EugÃ¨ne OudinÃ©     3                3  ...    4     4      37
4  6 avenue de la Porte de Champerret     3                3  ...    8    17      23
5                8 Boulevard Voltaire     0                0  ...    6     7       2
6                      37 rue Leblanc     0                0  ...    8    18      20
7         17 Rue des Luaps ProlongÃ©e     3                3  ...    4    22      13
8               34 avenue Jean Moulin     1                1  ...    2    22      58
9        41 boulevard de Rochechouart     6                6  ...    4    15       2

[10 rows x 25 columns]

# Accessing Information About the Dataset

In [6]:
# Checking the datatypes of the columns in the dataset
#
print(df_auto.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 25 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Address              5000 non-null   object
 1   Cars                 5000 non-null   int64
 2   Bluecar counter      5000 non-null   int64
 3   Utilib counter       5000 non-null   int64
 4   Utilib 1.4 counter   5000 non-null   int64
 5   Charge Slots         5000 non-null   int64
 6   Charging Status      5000 non-null   object
 7   City                 5000 non-null   object
 8   Displayed comment    111 non-null    object
 9   ID                   5000 non-null   object
 10  Kind                 5000 non-null   object
 11  Geo point            5000 non-null   object
 12  Postal code          5000 non-null   int64
 13  Public name          5000 non-null   object
 14  Rental status        5000 non-null   object
 15  Scheduled at         47 non-null     object
 16  Slots                5000 non-null   int64
 17  Station type         5000 non-null   object
 18  Status               5000 non-null   object
 19  Subscription status  5000 non-null   object
 20  year                 5000 non-null   int64
 21  month                5000 non-null   int64
 22  day                  5000 non-null   int64
 23  hour                 5000 non-null   int64
 24  minute               5000 non-null   int64
dtypes: int64(12), object(13)
memory usage: 976.7+ KB
None

In [7]:
# Checking for any null values in the dataset
#
print(df_auto.isnull().any())

print(df_auto.isnull().sum())

Address                False
Cars                   False
Bluecar counter        False
Utilib counter         False
Utilib 1.4 counter     False
Charge Slots           False
Charging Status        False
City                   False
Displayed comment       True
ID                     False
Kind                   False
Geo point              False
Postal code            False
Public name            False
Rental status          False
Scheduled at            True
Slots                  False
Station type           False
Status                 False
Subscription status    False
year                   False
month                  False
day                    False
hour                   False
minute                 False
dtype: bool
Address                   0
Cars                      0
Bluecar counter           0
Utilib counter            0
Utilib 1.4 counter        0
Charge Slots              0
Charging Status           0
City                      0
Displayed comment      4889
ID                        0
Kind                      0
Geo point                 0
Postal code               0
Public name               0
Rental status             0
Scheduled at           4953
Slots                     0
Station type              0
Status                    0
Subscription status       0
year                      0
month                     0
day                       0
hour                      0
minute                    0
dtype: int64

# Data Cleaning

In [8]:
# Irrelevant Data Observation: Dropping unneeded rows and columns
# Dropping rows that are not in the city of Paris over the month of April 2018.
#
rows_needed = df_auto[(df_auto["City"] == "Paris") & (df_auto["month"] == 4) & (df_auto["year"] == 2018)]
rows_reset = rows_needed.reset_index()
rows_reset

      index                             Address  Cars  ...  day  hour  minute
0         0                 2 Avenue de Suffren     0  ...    8    11      43
1         1           145 Rue Raymond Losserand     6  ...    6     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©     3  ...    4     4      37
3         4  6 avenue de la Porte de Champerret     3  ...    8    17      23
4         5                8 Boulevard Voltaire     0  ...    6     7       2
...     ...                                 ...   ...  ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry     0  ...    9    23       1
2812   4994                    15 rue de Rocroy     0  ...    1    20      49
2813   4996                   37 rue de Dantzig     4  ...    4    16      56
2814   4997                      142 rue du Bac     1  ...    1     7       1
2815   4999                 5 Rue Henry Brisson     4  ...    8    10       2

[2816 rows x 26 columns]

In [9]:
# Dropping the Cars column since it's equivalent to the "Bluecar counter" column all through the dataset.
# Dropping the "Displayed comment", "ID" and "Geo point" columns since no questions to be answered require these columns, thus not needed for the analysis
# Dropping the "Scheduled at" column since it only represents the "future" status which has no resources (Bluecar,Utilib,Utilib 1.4 and parking slots)
# 
rows_reset.drop(["Cars", "Displayed comment", "ID", "Geo point", "Scheduled at"], axis = 1, inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2816 rows x 21 columns]

In [10]:
# Dropping rows where the "Charging Status" column is "future" since they don't have resources
# 
rows_reset.drop(rows_reset.index[rows_reset["Charging Status"] == "future"], inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2816 rows x 21 columns]

In [11]:
# Dropping rows where the "Kind" column is "CENTER" since they also don't have resources
#
rows_reset.drop(rows_reset.index[rows_reset["Kind"] == "CENTER"], inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2813 rows x 21 columns]

In [12]:
# Dropping rows where the "Station type" is "subs_center" since they also don't have resources
#
rows_reset.drop(rows_reset.index[rows_reset["Station type"] == "subs_center"], inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2813 rows x 21 columns]

In [13]:
# Dropping rows where the "Status" column is "scheduled" since it reprsents those that have "future" rental status thus have no resources
#
rows_reset.drop(rows_reset.index[rows_reset["Status"] == "scheduled"], inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2804 rows x 21 columns]

In [14]:
# Dropping rows where the "Subscription status" column is "future" since it reprsents those that have "future" rental status thus have no resources
#
rows_reset.drop(rows_reset.index[rows_reset["Subscription status"] == "future"], inplace = True)
rows_reset

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2804 rows x 21 columns]

In [15]:
# Dropping rows where the "Rental status" is not "operational" or "broken" since they don't have resources
#
df_valid = rows_reset[(rows_reset["Rental status"] == "operational") | (rows_reset["Rental status"] == "broken")]
df_valid

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2804 rows x 21 columns]

In [16]:
# Checking, counting and dealing with any missing values in the dataset
#
print(df_valid.isnull().any())

print(df_valid.isnull().sum())

index                  False
Address                False
Bluecar counter        False
Utilib counter         False
Utilib 1.4 counter     False
Charge Slots           False
Charging Status        False
City                   False
Kind                   False
Postal code            False
Public name            False
Rental status          False
Slots                  False
Station type           False
Status                 False
Subscription status    False
year                   False
month                  False
day                    False
hour                   False
minute                 False
dtype: bool
index                  0
Address                0
Bluecar counter        0
Utilib counter         0
Utilib 1.4 counter     0
Charge Slots           0
Charging Status        0
City                   0
Kind                   0
Postal code            0
Public name            0
Rental status          0
Slots                  0
Station type           0
Status                 0
Subscription status    0
year                   0
month                  0
day                    0
hour                   0
minute                 0
dtype: int64

In [17]:
# Dropping any duplicate columns from the dataset
#
df_valid.duplicated()

df_valid.drop_duplicates()

      index                             Address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2804 rows x 21 columns]

In [18]:
# Fixing the messy columns in the dataset
#
df_valid.columns = df_valid.columns.str.lower().str.replace(' ','_')
df_valid

      index                             address  ...  hour  minute
0         0                 2 Avenue de Suffren  ...    11      43
1         1           145 Rue Raymond Losserand  ...     7      24
2         3              51 Rue EugÃ¨ne OudinÃ©  ...     4      37
3         4  6 avenue de la Porte de Champerret  ...    17      23
4         5                8 Boulevard Voltaire  ...     7       2
...     ...                                 ...  ...   ...     ...
2811   4992                     3 avenue d'Ivry  ...    23       1
2812   4994                    15 rue de Rocroy  ...    20      49
2813   4996                   37 rue de Dantzig  ...    16      56
2814   4997                      142 rue du Bac  ...     7       1
2815   4999                 5 Rue Henry Brisson  ...    10       2

[2804 rows x 21 columns]

# Exporting the Clean Dataset

In [0]:
# Export the clean dataset to a csv file
#
df_valid.to_csv('auto.csv')

# Data Analysis: Blue cars

# Question 1

In [20]:
# What is the most popular hour for returning Blue cars?
# This is the time where there are no more parking slots in the station since most people have returned the rented cars.
#
url = 'auto.csv'

clean_data = pd.read_csv(url)
clean_data

popular_hour = clean_data[clean_data ["slots"] == 0].groupby(["bluecar_counter"])["hour"].value_counts()
popular_hour

bluecar_counter  hour
0                21      17
                 3       13
                 20      12
                 2       11
                 14      11
                         ..
6                20       2
                 23       2
                 16       1
7                3        1
                 17       1
Name: hour, Length: 163, dtype: int64

# Question 2

In [0]:
# What is the overall most popular station?
# This is the station that has the highest number of Blue cars
#
overall_popular_station = clean_data[clean_data ["bluecar_counter"] != 0]["public_name"].value_counts().head(1)
overall_popular_station

Paris/Porte de Montrouge/8    11
Name: public_name, dtype: int64

# Question 3

In [0]:
# What is the most popular station at the most popular picking hour?
# This is the most popular station at 2100 hrs since the most popular returning hour is the most convinient time for renting a car
#
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["bluecar_counter"])["public_name"].value_counts().head(1)
most_popular_station

bluecar_counter  public_name
0                Paris/Tronchet/19    4
Name: public_name, dtype: int64

# Question 4

In [0]:
# What the overall most popular postal code for picking up Blue cars?
#
overall_popular_station = clean_data[clean_data ["bluecar_counter"] != 0]["postal_code"].value_counts().head(1)
overall_popular_station

75015    195
Name: postal_code, dtype: int64

# Question 5

In [0]:
# What is the most popular postal code at the most popular picking hour?
#  
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["bluecar_counter"])["postal_code"].value_counts().head(1)
most_popular_station

bluecar_counter  postal_code
0                75008          7
Name: postal_code, dtype: int64

# Data Analysis: Utilib cars

# Question 1

In [22]:
# What is the most popular hour for returning Utilib cars?
# This is the time where there are no more parking slots in the station since most people have returned the rented cars.
#
popular_hour = clean_data[clean_data ["slots"] == 0].groupby(["utilib_counter"])["hour"].value_counts()
popular_hour

utilib_counter  hour
0               21      52
                9       43
                19      40
                12      38
                1       35
                3       35
                10      35
                8       34
                22      34
                16      33
                2       32
                13      31
                0       30
                7       30
                11      30
                14      30
                15      30
                20      30
                5       29
                23      28
                6       27
                18      27
                17      25
                4       22
1               7        5
                11       5
                6        4
                14       4
                2        3
                10       3
                12       3
                13       3
                17       3
                22       3
                5        2
                8        2
                15       2
                16       2
                18       2
                19       2
                20       2
                21       2
                0        1
                3        1
                4        1
                9        1
                23       1
2               6        1
                8        1
                18       1
Name: hour, dtype: int64

# Question 2

In [0]:
# What is the overall most popular station?
# This is the station that has the highest number of Utilib cars
#
overall_popular_station = clean_data[clean_data ["utilib_counter"] != 0]["public_name"].value_counts().head(1)
overall_popular_station

Paris/Mac Mahon/5    4
Name: public_name, dtype: int64

# Question 3

In [0]:
# What is the most popular station at the most popular picking hour?
# 
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["utilib_counter"])["public_name"].value_counts().head(1)
most_popular_station

utilib_counter  public_name
0               Paris/Tronchet/19    4
Name: public_name, dtype: int64

# Question 4

In [0]:
# What the overall most popular postal code for picking up Utilib cars?
# 
overall_popular_station = clean_data[clean_data ["utilib_counter"] != 0]["postal_code"].value_counts().head(1)
overall_popular_station

75017    20
Name: postal_code, dtype: int64

# Question 5

In [0]:
# What is the most popular postal code at the most popular picking hour?
# 
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["utilib_counter"])["postal_code"].value_counts().head(1)
most_popular_station

utilib_counter  postal_code
0               75014          14
Name: postal_code, dtype: int64

# Data Analysis: Utilib 1.4 cars

# Question 1

In [23]:
# What is the most popular hour for returning Utilib_1.4 cars?
# This is the time where there are no more parking slots in the station since most people have returned the rented cars.
#
popular_hour = clean_data[clean_data ["slots"] == 0].groupby(["utilib_1.4_counter"])["hour"].value_counts()
popular_hour

utilib_1.4_counter  hour
0                   21      43
                    12      35
                    9       34
                    19      34
                    2       33
                            ..
2                   13       1
                    14       1
                    19       1
                    20       1
3                   13       1
Name: hour, Length: 62, dtype: int64

# Question 2

In [0]:
# What is the overall most popular station?
# This is the station that has the highest number of Utilib 1.4 cars
#
overall_popular_station = clean_data[clean_data ["utilib_1.4_counter"] != 0]["public_name"].value_counts().head(1)
overall_popular_station

Paris/Porte de Montrouge/8    7
Name: public_name, dtype: int64

# Question 3

In [0]:
# What is the most popular station at the most popular picking hour?
# 
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["utilib_1.4_counter"])["public_name"].value_counts().head(1)
most_popular_station

utilib_1.4_counter  public_name
0                   Paris/Tronchet/19    4
Name: public_name, dtype: int64

# Question 4

In [0]:
# What the overall most popular postal code for picking up Utilib cars?
#
overall_popular_station = clean_data[clean_data ["utilib_1.4_counter"] != 0]["postal_code"].value_counts().head(1)
overall_popular_station

75017    36
Name: postal_code, dtype: int64

# Question 5

In [0]:
# What is the most popular postal code at the most popular picking hour?
# 
most_popular_station = clean_data[clean_data ["hour"] == 21].groupby(["utilib_1.4_counter"])["postal_code"].value_counts().head(1)
most_popular_station

utilib_1.4_counter  postal_code
0                   75019          13
Name: postal_code, dtype: int64